### ISSUE TITLE
Achievements using Google Play Game Services

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#205]
A couple of people have requested this, but I need to look into whether I can avoid any inconvenience for users who don't have the Google extras on their phone (e.g. running AOSP builds), or don't have an account, or don't want to publish game activity on their account, etc. I would want it to be something like a menu item "Achievements" which just isn't there if you don't have a Google account set up, and the first time you click it you need to sign in - I don't want to get in the user's face about it, and I want to make sure Google won't automatically get in the user's face about it on my behalf if I include the necessary Play Services library.

**Comment by chrisboyle** [comment]
寶力龍 writes:
> hoping there will be a function to record my scores made in each game

**Comment by chrisboyle** [comment]
Antonio Monteiro writes:
> These puzzles are missing an objective...
> Just count the number of wind/losses will make it more interesting :)

**Comment by chrisboyle** [comment]
lotus_mud writes:
> its fun but it would be awesome to have some statistics. how long to solve a puzzle type. how many solved etc

**Comment by chrisboyle** [comment]
Michael Štědrý writes:
> I found out that I am measuring how long it takes me to solve a puzzle and it is much more fun to do so. Right now I do it on my wrist watch, but it would be much more convenient to have such an option in the game.
>
> For starters it would be enough to display the time after you finish the game. Later you could add a personal high score table. I would avoid global stats display, since that attracts cheating.
>
> You could also get some relative ranking information for each generated level.

**Comment by chrisboyle** [comment]
Phillip Hankins writes:
> Hmm, good ideas there... especially the one about starting with something small and low/no impact, like just an option to show the time taken on a game after it is solved is a good entry.
>
> After that, exporting times or a win/loss note info for the past SomeNumber of games to a text file somewhere would be nice, then that info could be read/used by a separate app to do whatever stats the user finds fun/useful...chaining tools together and all that old school unix philosophy stuff.  In that vein, I suppose the high class, modern android way would be for the puzzle game to send some broadcast out with the game info and let whatever gameStatisticsFun app the user has receive that. 

>And that takes the subject back to using google play game services, so maybe I just retraced your thinking.  I'm not familiar with the game services (beyond playing a game or two that uses them a little).  Are they able to record and recall info on all the times a user plays a game? So that I can eventually get a pretty graph of completion times for some game going back years, or a chart of times as binned by the day of the week or time of day.

**Comment by jnahmias** [comment]
Please only do this if it is unobstrusive to those that don't have Play Services.  I do not have, nor do I want, a Play account; so, please make it so that there isn't a strong dependency.

**Comment by chrisboyle** [comment]
Amp writes:
> Would it be possible to have the games save number of wins/losses?

**Comment by chrisboyle** [comment]
+1 from Abdul Vahit IŞIK

**Comment by chrisboyle** [comment]
These days I feel this would be too big a difference compared to the other platforms, see [README.md](https://github.com/chrisboyle/sgtpuzzles/blob/main/README.md). In the unlikely event that upstream adds an achievements system then I'll replicate it, and that could involve Google Play Games, but I don't want to arbitrarily define a bunch of Android-specific achievements.
