### ISSUE TITLE
Filling: selected/completed greys too similar

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#236]
Found by Alex. Consequences include not noticing that you've accidentally selected part of a completed region and overwriting it.

**Comment by bjh21** [comment]
For the record, I just committed the fix for this upstream as af2d992af0d11ad2a91b4c1f7c04d6c69dbe6e55.
https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=af2d992af0d11ad2a91b4c1f7c04d6c69dbe6e55
