### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mnabilmughal** [chrisboyle/sgtpuzzles#247]
I am trying to build the sgtpuzzles but I am unable to do it after trying couple of hours I am asking here what I am doing wrong with it. 
Following is the error I am getting. 

Error:(112) Execution failed for task ':app:compileDebugNdk'.

> Process 'command '/Volumes/Entertainment/Softwares/android-ndk-r9d/ndk-build'' finished with non-zero exit value 2

I have added the path of my ndk in local.properties file as you mentioned. Here is the path line 

ndk.dir=/Volumes/Entertainment/Softwares/android-ndk-r9d

Can anyone please help me about this issue.

**Comment by chrisboyle** [comment]
Hi, sorry I didn't reply to this at the time. Is this still an issue with current Puzzles and the latest NDK? If so, please paste a more complete error log, as the lines quoted here only say that something unspecified went wrong building the JNI component which is most of the project. Earlier lines, or lines in the Gradle Console, should give more detail. Thanks.

**Comment by mnabilmughal** [comment]
Hello, thank you for reaching back. I willl retry it and will show you
complete error log. Thanks

**Comment by chrisboyle** [comment]
Log never received, so hopefully you found a solution. Current `master` branch builds fine for me in current Android Studio beta (2.3.x). If it doesn't for you, please reopen with a more complete log.
