### ISSUE TITLE
Shift-like button for right-click

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#25]
From Alexander Gavrilov:

> Would it be possible to add a special toggle button to a mini-keyboard at the bottom of the screen which basically locks the tap as a right-click emulation? So, if this special button is toggled, all subsequent taps on the screen will be recognized as right clicks. Un-toggling the button would yield usual left-clicks.

I think ideally this would work like shift on Android keyboards: tap once to affect the next tap, tap twice to lock (with clear indication on the button).

**Comment by tdionizio** [comment]
Is this feature still being considered to be added?
I miss something to make the "right-click" action the default, for example, I play Loopy almost exclusively with right-click and only use left-click at the end to mark the path, and using the long touch action repetitively takes too much time...
