### ISSUE TITLE
Singles: make show hidden numbers action optional

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#256]

**Comment by yashpalgoyal1304** [comment]
hey, how can i show the hidden numbers?

i didn't see any settings in there...

i was playing the singles game the other day, and really felt the need to see which numbers i have "removed" or painted over.

the solution i thought was that the paint to have some transparency to it.

**Comment by chrisboyle** [comment]
There currently isn't an option for it, hence this issue. This is a hidden feature from upstream, it's not even a button-press: you have to click outside the grid ([singles.c:1529-1531](https://github.com/chrisboyle/sgtpuzzles/blob/3ae4a036d8ef888154ff8419ca2a441f4826fde9/app/src/main/jni/singles.c#L1529-L1531)). This should be made more accessible. I imagine Simon's comment about "per-game option" there means chosen at game-start time (as it affects difficulty?) which is another interesting possibility.

**Comment by yashpalgoyal1304** [comment]
> you have to click outside the grid 

wow, it's awesome that it works on android too. thanks for letting me know about this hidden feature :)

**Comment by chrisboyle** [comment]
Simon did this in commit 92ac45fe240b2063455b0b01dedc6ef6996f18af, and it's included in current beta builds.
