### ISSUE TITLE
Tracks: missing column/row error indication

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#266]
Reported by FlopEJoe:

> Also, there are some cases in Tracks where I would expect a red error indication but it doesn't show up. In the attached, I expected rows (from the top) 1 and 2 to show a red 3 and 4 count because that criteria isn't satisfied. I'm not sure what should trigger the red error. If it's too irritating to flash on and off with every change, maybe a completed but wrong track?

![tracks](https://cloud.githubusercontent.com/assets/127305/8394228/35162394-1d26-11e5-9756-f9126067761c.png)

**Comment by tdionizio** [comment]
Usually the red numbers are only shown when the **criteria is exceeded**, which doesn't happen in this case. This is what happens in most games with this kind of behaviour.
Also, the game isn't complete, because the top 2 rows don't meet the criteria and column 4 (with the hint 5) isn't met either. For the game to be complete all hints must be satisfied.

**Comment by chrisboyle** [comment]
I think the best compromise here is having under-filled clues also go red when a complete single path exists as suggested in the initial report. Otherwise a user might wonder why the game isn't considered complete.

**Comment by chrisboyle** [comment]
Confirmed still an issue today.

**Comment by bjh21** [comment]
I think I've just fixed this upstream with commit 99d3c31e12ac5bb7c12d2b7a59c702cb671e9b62 (https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=99d3c31e12ac5bb7c12d2b7a59c702cb671e9b62).  With the game above (ID `8x8:hCAmCb3p6a5k9f,2,S4,7,5,3,3,4,4,3,S4,5,6,5,6,1,2`), the game highlights the three unfilled row/column clues when the track is completed.

**Comment by chrisboyle** [comment]
Thanks, LGTM
