### ISSUE TITLE
Undead: Screen rotation temporarily clears clue done marker

### ISSUE THREAD

**Issue by me-and** [chrisboyle/sgtpuzzles#273]
When playing Undead, mark some clues as done (i.e. tap them and they go grey). Cause the screen to rotate. The clues that were marked as done will unexpectedly revert to black, but tapping anywhere on the screen will cause all the previously marked clues to turn grey again.

**Comment by chrisboyle** [comment]
Nice catch. :-) Magnets and Towers get this right, so it shouldn't be too hard...
