### ISSUE TITLE
Signpost night mode: grey text is less readable

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#279]
The text could remain black in night mode; it never appears on a black background (that's only used for unnumbered unconnected tiles).

**Comment by ffes** [comment]
Similar readability issues in night mode happen in other games as well.

Solo (aka Sudoku): In night mode the blue pencil marks and the green numbers are hard to read, especially when the background of the cell is (partially) grey. Lighten up those colors might help.

Guess (aka MasterMind): the small black dot (colour on right place) is more difficult to understand, being black (with grey border) on black background. The empty grey space stand out more then the black one. But maybe that is just a matter of getting used to.
