### ISSUE TITLE
Better victory animation in Tracks

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#283]
Stuart Monty says

> I know that it's a bit out of character for the game collection, but it would be totally wicked if there were a little train that ran the track when you won.

**Comment by bjh21** [comment]
It's not a little train, but I've just pushed an upstream change that causes the victory flash in Tracks to run along the track: 425942c852f22d7d94f7643696522d32c0b02067 (https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=425942c852f22d7d94f7643696522d32c0b02067)

**Comment by chrisboyle** [comment]
I like the new victory flash; I agree that an actual train would be out of character and I think nobody's likely to implement it, so closing this.
