### ISSUE TITLE
Swap-L-R toast too frequent

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#300]
One "on" and one "off" per game would be sufficient? Or just disable altogether once you've seen two ons and two offs ever?

**Comment by tdionizio** [comment]
How about enabling the behaviour of long-press showing the tooltip without performing the associated action? This is the behaviour in the top toolbar (for reference).

**Comment by chrisboyle** [comment]
Worth doing as well, but I don't think it's sufficiently widely known for that to be the only way to get a text description of what it does (which it would be on games that don't show arrows by default).

**Comment by tdionizio** [comment]
Maybe add an option on global settings enabling the "long press show description" behaviour, and as you mentioned showing the description for the first few times you use the button and then disable the toast clicking the button.

**Comment by chrisboyle** [comment]
I was thinking make that always available, in addition to the toast first few times. There are lots of options already, I'm wary of adding more clutter to that screen. We could consider such an option if anyone had a convincing reason to ever turn it off (do you?) or if some future control scheme involved long press on the buttons for a different action.

**Comment by chrisboyle** [comment]
Also it would be useful to have long press descriptions for other buttons at the bottom of the screen, but I'll split out a separate issue for that.

**Comment by tdionizio** [comment]
If I remember correctly, the reason I started to know about the long press behaviour was because I noticed it on some other app within some settings screen, which worked as a hint for "you can do this" to get descriptions of what the buttons do. Apart from that, can't see any reason to turn it off or even being in the settings :)

**Comment by lzeisset** [comment]
Awesome! Thanks for the fix!
