### ISSUE TITLE
"New game" while swapped -> 2 left buttons

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#311]
Reported by Puggan:

> Tracks:
> 1. Have show arrow keys on
> 2. Activate swapped press
> 3. Start a new game.
> = both button shows the "lay track"-icon, (no button have the "not a track"-icon)

(not specific to Tracks)

**Comment by puggan** [comment]
Bugged view:
![pic_20150808_113740](https://cloud.githubusercontent.com/assets/866668/9150005/bb59d630-3dc4-11e5-9d6a-e47cd20b0832.jpg)

Normal view:
![pic_20150808_113815](https://cloud.githubusercontent.com/assets/866668/9150006/c2d14506-3dc4-11e5-83ed-152bd5e57255.jpg)
