### ISSUE TITLE
Undo "New game" / similar operation

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#312]
Currently you can accidentally wipe a game that you were playing for ages and wanted to keep, but hadn't bothered to save. While a full game history has a lot of complications, a simpler fix would be to allow the Undo button to undo one "New game" or similar operation, if clicked before leaving the gameplay screen.

**Comment by mquevill** [comment]
[Fixed in upstream](https://git.tartarus.org/?p=simon/puzzles.git;a=commit;h=b9b73adb53b3ffb09a2e8c9682351bf892634470) (and a few more recent commits)

**Comment by chrisboyle** [comment]
Merged (#442), but in fact reimplemented for Android:
* fd5d49908387a86e2ead499c1e9305080da81279
* da53fd36d09ff2bb58e053193eed056c57a617dc
* 5777fa9cc74c355af5b6bd1caad1720819e3862a
* 81b10c8c14da69906652acb54b40c0f9fe9d3b16
