### ISSUE TITLE
Pearl docs missing parameters

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#320]

**Comment by AkiTensai** [comment]
Sentences in [brackets] is a section I'm not certain I'm speaking truthfully about.
"36.2 Pearl parameters

Pearl allows you to configure two separate dimensions of the puzzle grid: the number of columns, and the number of rows, into which the main grid is divided.

You can configure the difficulty of the generated puzzles with the 'Difficulty' drop down. [The easy difficulty usually has progression along a required route. The tricky difficulty sometimes requires looking ahead along a route further to know which way the loop goes.]

If you tick the ‘Allow unsoluble’ checkbox, Pearl's generator won't require a puzzle to have a single valid solution."

**Comment by chrisboyle** [comment]
I'm not sure when this was fixed but it's definitely present in the help now.
