### ISSUE TITLE
Some small games can start pre-solved

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#334]
Fixed for Galaxies in 3e03338b7e7bad1f7db06695d44439dcfbdef6a6; now also seen in Flood and, I think, Fifteen.

**Comment by bjh21** [comment]
The Flood and Fifteen fixes are now upstream as f967bfa87b6ea08434501558e0c41184fdce333d
(https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=f967bfa87b6ea08434501558e0c41184fdce333d)

(The Galaxies fix was already there as f9027226a05b6e2fc49d0256262edc6cc3a8c569)
