### ISSUE TITLE
Light Up spins when asked for a 2x2 game with 4-way symmetry

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#335]

**Comment by bjh21** [comment]
For the record, I just committed the fix for this upstream as cbf2ede64ad91346e6399603ff7b8df432be5a06
https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=cbf2ede64ad91346e6399603ff7b8df432be5a06
