### ISSUE TITLE
Magnets incorrect message about minimum width

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#336]
says "at least one" when min is actually 2

**Comment by bjh21** [comment]
For the record, I just committed the fix for this (with i18n removed) upstream as 69e63a810e0bd6f85a46d8490c6e366237e061ef.
https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=69e63a810e0bd6f85a46d8490c6e366237e061ef
