### ISSUE TITLE
Magnets spins when asked for 2x2 game

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#337]

**Comment by chrisboyle** [comment]
Applies even at 4x4, says Jasper Lieber.

**Comment by jasperlieber** [comment]
but only if "tricky" is selected -- other option works just fine...

**Comment by chrisboyle** [comment]
Fixed in 133794977a13767e0c1596be6a5b26f2cf2d1fd1.

**Comment by bjh21** [comment]
For the record, I just committed the fix for this (with i18n removed) upstream as 69e63a810e0bd6f85a46d8490c6e366237e061ef.
https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=69e63a810e0bd6f85a46d8490c6e366237e061ef
