### ISSUE TITLE
New game confirmation

### ISSUE THREAD

**Issue by pakhomchik** [chrisboyle/sgtpuzzles#351]
Hi.
Thanks for your port.
With my 5.5" screen sometime when I try slide down a notification bar I press New game button and select some item from it. Confirmation dialog is needed to prevent this. Thanks and sorry for my english.
example: https://www.youtube.com/watch?v=Vbr-8N2yFLc

**Comment by chrisboyle** [comment]
Hi, thanks for your bug report. This is already open as #347 where I have written some thoughts on how best to fix it (I don't want to just **always** have a confirmation dialog when throwing away a game, but maybe if the menu was invoked very quickly...). Please do comment on #347 with any further thoughts.
