### ISSUE TITLE
Required faketouch system feature is unknown on Android 2.x

### ISSUE THREAD

**Issue by zvr** [chrisboyle/sgtpuzzles#352]
The application requires the _faketouch_ system feature; otherwise it cannot be installed.

This feature was introduced in Android 3.0 (API level 11) -- so devices running older systems like Froyo (2.2) and Gingerbread (2.3) are not able to install the package.

**Comment by chrisboyle** [comment]
Embarrassingly this has been the case since [2014-11-07-0016-4a8edc](https://github.com/chrisboyle/sgtpuzzles/releases/tag/2014-11-07-0016-4a8edc).
