### ISSUE TITLE
Dominosa highlight buttons broken after 9

### ISSUE THREAD

**Issue by Dorus** [chrisboyle/sgtpuzzles#362]
Not only is the 0 button missing (#359 ), also, if you pick 10 or more dominoes, you get non-functional buttons 

    : ; < = > ? @ A B C D ...

I tried up to 40 (shouldn't be playable but ok), R and U are replaced with the undo and redo buttons.

**Comment by chrisboyle** [comment]
Good catch, thanks! The underlying functionality on other platforms doesn't allow highlighting things higher than 9 (it lacks a way to input multiple digits), so the fix on Android will have to be to just limit the buttons to 9.

**Comment by Dorus** [comment]
You can always substitute A, B, C, D for 11, 12, 13 14. Go HEX :)

Because with highlight, 12 size Dominosa is very playable.

**Comment by chrisboyle** [comment]
That's what e.g. Solo does, yes, but I can't expect users to match up 10 on the board with A on the button, and I won't unilaterally change Android to display A where other platforms display 10. I'll have to talk to Simon about how the other platforms are going to solve this problem.

**Comment by Dorus** [comment]
My suggestion would be to do what Solo does then: Also use A on the field, instead of 10. Than A matches up to A.

**Comment by chrisboyle** [comment]
I've emailed Simon; the above fix will have to do until there's a reply.
