### ISSUE TITLE
[Game request] Flow free bridges

### ISSUE THREAD

**Issue by ildar** [chrisboyle/sgtpuzzles#386]
I wonder if a game similar to [this](https://play.google.com/store/apps/details?id=com.bigduckgames.flowbridges) available? Or are there any plans to add one?

**Comment by chrisboyle** [comment]
No such plans from me, but this is not at all Android-specific so is better directed upstream to Simon; see [his page](http://www.chiark.greenend.org.uk/~sgtatham/puzzles/).

**Comment by ildar** [comment]
oh! you're right, thanks.
