### ISSUE TITLE
Add a confirmation for new game and restart

### ISSUE THREAD

**Issue by tmp6154** [chrisboyle/sgtpuzzles#388]
Today I've been playing 9x9 normal Keen grid. I've almost solved one and I wanted to check whether I did correct deduction for certain square. I've opened the menu to tap "Show solution" but then my finger slipped a little lower and I've accidently pressed "New game". The grid was gone (probably forever) and this puzzle was left without a solution.

While on desktop it's more difficult to accidently click the wrong option in the menu, it's more of a problem with touchscreen. I propose to add a confirmation message for "new game" and, maybe "restart" option to prevent accidental loss of progress or entire puzzle, as this would be easiest way to prevent accidental clicks.

**Comment by chrisboyle** [comment]
I'm merging this ticket with #312: I think Undo is better than confirmation as it's less obtrusive on all the occasions when it's not needed. Note that Restart can already be undone (upstream feature). So the task would be to allow Undo for "New game" and selection from the Type menu (pencil icon). This is relatively easy: just save into some in-memory buffer before actually invoking said operations, and special case "Undo" from the start of the undo chain to restore from such a save if it's still around.

A Toast the first few times New game / similar is clicked on an incomplete game, to tell the user that this is possible, would probably not go amiss.
