### ISSUE TITLE
Signpost: Fixed pieces will not be marked when they are part of an error. 

### ISSUE THREAD

**Issue by MaPePeR** [chrisboyle/sgtpuzzles#391]
When you have an error in Signpost that involves one of the "signs" from the fixed initial board position (blue text) these will not show the error. Only the other conflicting piece will be marked.

**Comment by mquevill** [comment]
I believe this is already solved in both upstream and here.
![signpost](https://user-images.githubusercontent.com/17033543/37994001-2ac563b2-31de-11e8-8871-a1c247a18f36.png)
[signpost.txt](https://github.com/chrisboyle/sgtpuzzles/files/1853739/signpost.txt)

**Comment by chrisboyle** [comment]
Yep, seems to work for me, reopen with save-file if seen.
