### ISSUE TITLE
Galaxies big zone not recognized

### ISSUE THREAD

**Issue by Xaxetrov** [chrisboyle/sgtpuzzles#393]
I am on a 10/10 unreasonable galaxies game and the center tile won't highlight... I am pretty sure I didn't make mistakes. MP me if you want a screenshot

**Comment by chrisboyle** [comment]
Hi, sorry for the delay in getting back to you. A saved game is actually what I would need to investigate this. You can get this from within the app, using Save or Share (in the Game menu, the checkerboard one).

**Comment by mquevill** [comment]
I haven't been able to replicate on 10x10 unreasonable difficulty.

**Comment by Xaxetrov** [comment]
Can be closed.
