### ISSUE TITLE
Cube custom games not always solvable

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#398]
Fabian Röling writes:

> "Cube" can generate impossible levels. It can put a cube on a 1x7 grid.

**Comment by mquevill** [comment]
Solved in [upstream](https://git.tartarus.org/?p=simon/puzzles.git;a=commit;h=55be8e50db2c103850c95db879c02cd945c36d5f).

**Comment by chrisboyle** [comment]
Merged for next release, see #442.
