### ISSUE TITLE
Solo: checklist

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#414]
deeLaw writes:
> Have a checklist of numbers at the top, if I've used all 9 instances of a number it should be green, and if I tap on the number it would highlight all of that number on the board

**Comment by hXtreme** [comment]
This is a highly anticipated feature, are there plans to implement it in near future?

**Comment by goyalyashpal** [comment]
hi! as u've already recognised this at https://github.com/chrisboyle/sgtpuzzles/issues/590#issuecomment-1413791945 i think this issue is totally covered by (& hence a duplicate of) #357

is there any reason u considered to keep both open :smiley:

**Comment by goyalyashpal** [comment]
oh yeah, found the one issue i stumbled upon before any of these 3: https://github.com/chrisboyle/sgtpuzzles/issues/201

**Comment by chrisboyle** [comment]
No, let's consolidate to #357
