### ISSUE TITLE
Tighten custom game param limits in Solo?

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#435]
Fabian Röling writes:
> In "Solo" there are some configurations that are allowed, but take infinitely long to generate, for example the one in the attached screenshot.

![screenshot_2017-10-19-20-39-50](https://user-images.githubusercontent.com/127305/32547576-c8a1ccdc-c47a-11e7-9389-3b3425813c94.png)

**Comment by mquevill** [comment]
This takes infinitely long because it's impossible; 2x1 and 3x1 should not be allowed in x-type games. This is now fixed in upstream.

**Comment by chrisboyle** [comment]
Merged for next release, see #442
