### ISSUE TITLE
Re-unpack game generation executable if missing / improperly installed

### ISSUE THREAD

**Issue by Viqsi** [chrisboyle/sgtpuzzles#438]
See screenshot. Any attempt to open and play any of the puzzles on my Galaxy Note 8 (running Android Nougat 7.1.1) ends with this message - "Game generation exited with status 134" - and then immediately backs out to the list of puzzles.

![tempfileforshare_20180129-205158](https://user-images.githubusercontent.com/6570923/35544071-86045c58-0536-11e8-9f76-77d40cd41806.jpg)

**Comment by chrisboyle** [comment]
That's weird. Please could you confirm:

* that you installed this from Google Play (not e.g. F-Droid, who have produced builds broken in this way in the past)
* and that the version number at the bottom of Puzzles' Settings screen is `2016-12-25-0906-0b34887`.

And in any case, perhaps try reinstalling the app?

Thanks

**Comment by Viqsi** [comment]
Confirmed that that's the same version.

The APK was downloaded from Google Play, but not directly installed from same - I was restoring from backup, having gotten a new phone. Looks like that was the cause of the problem, tho, because I did try uninstalling and reinstalling, and that seems to have gotten rid of the error.

It's been fine previously when I've migrated it, or else I might have thought to try that. Feeling a little embarrassed now. ;)

**Comment by chrisboyle** [comment]
Oh, yes, the restore from backup explains it. After installation, Puzzles has to unpack and place an executable file in its data directory; this executable handles generating a new game. I can see how a restore from backup might have omitted such a file, or given it the wrong permissions or owner.

I'll leave this issue open to reflect that Puzzles should be more resilient to such situations, re-unpacking the executable if required (or explicitly ask for re-install if there's some immovable obstacle in the way).

Thanks again for the report, and glad it's working again.

**Comment by chrisboyle** [comment]
This can no longer happen (as of the next release) because we use the copy of the executable that the system unpacks for us.
