### ISSUE TITLE
Solo X/jigsaw/killer completion with error

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#440]
Reported by Maarten Daalder: enter a 4 in the remaining space and you get the completion popup, even though there is an error on a diagonal (correctly highlighted).

https://drive.google.com/file/d/19_zELyZowEtjzvqOnR0mcsGxDipGNPVF/view?usp=drivesdk

![screenshot_2018-02-16-20-38-32](https://user-images.githubusercontent.com/127305/36328516-5526fe38-135a-11e8-9049-e9d5dc6fa54e.png)

**Comment by x-sheep** [comment]
This occurs in upstream as well.

**Comment by x-sheep** [comment]
This is fixed in the most recent upstream commit.

**Comment by chrisboyle** [comment]
Merged for next release (see #442)
