### ISSUE TITLE
Merging with upstream

### ISSUE THREAD

**Issue by x-sheep** [chrisboyle/sgtpuzzles#442]
The last time this project merged with upstream was December 2016. A lot has changed since then, and it could be beneficial to merge incrementally, instead of going straight to the latest version.

I've compiled a list of major changes (commit hashes) and some notes based on my own experience of maintaining a port, which I hope is useful.

## Rework the preset menu system to permit submenus.
a7dc17c4258837b0ee3927f1db5e1c02acee5cc3

The preset menu API has been completely replaced, and now allows submenus. Presets are no longer identified by index. This is currently only used to put half of Loopy's presets under a "More..." submenu.

## Generate special fake keypresses from menu options.
e4d05c36d996c3053a66ca29cfe84e9652d501e3

Frontends should now send constant values such as `UI_UNDO` for menu actions, instead of sending the letter `'u'` to the midend.

## New name `UI_UPDATE` for `interpret_move`'s `return ""`.
eeb2db283de9115f7256fa4cc49597d63e06b0ab)

This doesn't require a change in the frontend, but all modifications in `interpret_move` functions should return `UI_UPDATE`. Returning `""` will cause a crash.

## Use a proper union in struct `config_item`.
de67801b0fd3dfa11777c1ef86cd617baf376b7b

The custom configuration menu should use the new names.

## midend: Allow "new game" to be undone / Permit redoing past an undone New Game action.
5247edd16dac8f673a03619e1aae76bf10f8eb43

Users can now undo and redo a single New Game action, provided the parameters stay the same. This probably won't immediately work in this port, since the midend doesn't actually create new games, but loads games generated by a subprocess.

Switching between a completed/unfinished game might cause the "Game Completed" screen to appear at inappropriate times.

## Add a request_keys() function with a midend wrapper.
60a929a250cf4f7f87ac082e5705f9a838a7f8c8

There is now a function in every puzzle that returns the buttons that should be used on the virtual keyboard. The default implementation only includes essential keys, not buttons that make playing the game easier (e.g. the number highlighting in Dominosa).

**Comment by chrisboyle** [comment]
Thanks, this is helpful

**Comment by chrisboyle** [comment]
Current progress on master: done submenus and `UI_UNDO`/`UI_REDO` (other `UI_*` actions being irrelevant/handled differently on Android).

Probably need to redo cursor visibility toggling in at least Net (check Tracks too).

**Comment by chrisboyle** [comment]
`master` is now up to date with upstream. I have a few more things to fix before releasing this. #444 would be nice due to the new rolling upgrade requirements, and I need to review other issues.
