### ISSUE TITLE
Toggle swap L/R with stylus button

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#449]
Bruno Garcia writes:
> Toggle flag mode by clicking the button on a stylus (s open on my case, not sure if all of them have it) would be much appreciated

I don't have that hardware (stylus, but I have no button) so I can't test this.

**Comment by omgitsraven** [comment]
If it helps any: at least with an S Pen on a Galaxy Tab S7+, tapping the button does nothing, but if I hold the button and then drag on the screen, the puzzle zooms in as I drag. (This doesn't seem to be a system-wide gesture; I actually haven't yet found any apps besides this one that produce that result!) I was going to suggest "L/R are swapped while stylus button is held", so this could be a starting point, if anyone knows what gesture the app is receiving that's causing the zoom?

**Comment by omgitsraven** [comment]
I've just made a pull request for this! https://github.com/chrisboyle/sgtpuzzles/pull/498

To be clear, mine swaps only as long as the button is held, rather than toggling upon tapping the button; hopefully that's what the original commented had in mind? (Or at least, hopefully it's something they'd be satisfied with!)

**Comment by yashpalgoyal1304** [comment]
> but if I hold the button and then drag on the screen, the puzzle zooms in as I drag

this game zooms in when i pinch with 2 fingers, and pans on dragging with 2 fingers. so, do u have any way to check if that's the what the machine is getting as input on doing what u did??

> I actually haven't yet found any apps besides this one that produce that result!

can u try on one of the galaries app which support pinch to zoom while viewing photos?? like simple gallery by tibor kaputa maybe?

**Comment by chrisboyle** [comment]
Now that I finally got around to merging the PR #498 I think this can be closed too.
