### ISSUE TITLE
Unopenable — repeated crashes on LG Q7+

### ISSUE THREAD

**Issue by TaperW** [chrisboyle/sgtpuzzles#456]
I've just gotten a new LG Q7+,  running Android 8.1.0 and the latest T-Mobile updates, and Puzzles refuses to open, reporting "Puzzles has stopped" and "Puzzles keeps stopping".

(I sent the automated feedback via Google, but I don't know the destination of those.)

**Comment by chrisboyle** [comment]
Hi, thanks for your report. I do get automated reports from Google but they're not very informative. On you new device, was Puzzles installed by Play Store (either automatically or manually), or did you use some sort of third-party backup/restore application? Some of those third-party apps can sometimes leave out a file relating to the game generation process and Puzzles doesn't handle that well yet.

In any case, could you perhaps try uninstalling it and reinstalling it from Play Store, and let me know if that helps?

I take it this happens before Puzzles has shown anything at all? Is there a flash of the list of games, or just an immediate crash dialog?

**Comment by chrisboyle** [comment]
Closing due to lack of info - do reopen if you're still experiencing crashes and can give details
