### ISSUE TITLE
Stop undo/redo across game boundary when button held down

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#460]
Suggestion from Roland Illig:
> When I press and hold the undo button, it should only go back to the beginning of the current game.
>
> When I'm already at the beginning of a game and the button is currently released, when I press it now, it should jump over to the previous game.
>
> This arrangement would allow me to quickly and accurately navigate to the beginning of the current game. (I often need exactly this when I'm stuck in a dead end.) Navigating to the previous game needs some extra work but would still be intuitive and quite fast.

**Comment by mquevill** [comment]
Perhaps an extra dialog box to confirm the undoing of the new game would be helpful? I think that holding the undo should stop at the beginning of the current game, and pressing it again should prompt a confirmation dialog to undo the new game.

**Comment by chrisboyle** [comment]
Stopped on holding the button down, in b3d2ce90bdfe66bf3e05967775e5ab75a677f5eb (and a toast when it happens). I felt that a dialog would be too in-your-face.
