### ISSUE TITLE
Update F-droid

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#465]
Should be easier now that the game generation executable is part of the standard Gradle build.

**Comment by JonnyTech** [comment]
When will we see an update on F-droid? Last release was`Version 2018-10-27-1350-f281644b (117)`.

[Maintainer notes](https://f-droid.org/wiki/page/name.boyle.chris.sgtpuzzles#Maintainer_Notes) show:

> Auto-Update disabled for now as the upstream RepoManifest is providing ${timestamp()}-${idForSimon()} as the current version.

**Comment by chrisboyle** [comment]
As soon as someone volunteers to do it. There's no particular reason it has to be me, and I'm a bit busy.

That maintainer note describes a reason the APK version number can't be automatically detected from a source checkout because the version number is an automatically generated timestamp. If F-Droid has a way to look at git tags instead, that would work, if someone volunteers to find out and use that.

**Comment by JonnyTech** [comment]
So there is a difference in building for the Play Store?

I thought that for f-droid you just tag a new release version and their system automagically builds it.

**Comment by chrisboyle** [comment]
Now that the game executable is part of the standard Gradle build, there shouldn't be any special effort required to build it - but testing any build before releasing it is still a good idea, and is something F-Droid's model doesn't address because nobody is responsible for that in an automated scenario; this has bitten Puzzles before.

See my previous comment for the reason F-Droid's usual method of detecting that a new release has happened doesn't work for Puzzles.

**Comment by JonnyTech** [comment]
Hi, have you (or anyone else) been able to sort out the issue of getting newer releases tagged correctly for fdroid? Shall I ask on their repo/forum?

**Comment by chrisboyle** [comment]
I've submitted a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10976) for this.

**Comment by chrisboyle** [comment]
They've merged it but it will be [about two to four days](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client) before it's visible. Future updates should only need another similar block adding near the end of the file and the Current* lines at the end updating.

Still unclear on automatic updates: it looks like their system **can** look at tags but may still be disrupted by the dynamic `versionName`, and it's not immediately clear to me whether it'd preserve the customisations declared under the previous version. In any case, now that I know what's needed I'm happy to send them an MR occasionally.

**Comment by JonnyTech** [comment]
Version 2022-04-29-0852-c43a34fb-fdroid is now available from F-droid, thank you very much.
