### ISSUE TITLE
Filling allows 2x2 -> spin

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#467]

**Comment by mquevill** [comment]
The upstream version is able to allow for any size (1x1, 1x2, 2x1, 2x2, etc.), though there is special logic for the 2x2 case (https://git.tartarus.org/?p=simon/puzzles.git;a=blob;f=filling.c;h=80a3c6ec9279aa09ffd8923e260be516e53955d2;hb=HEAD#l386) Not sure if changes made in the last ~2 years affected this or if it's specific to this implementation.

**Comment by chrisboyle** [comment]
Seems to work in current source (with upstream recently merged).
