### ISSUE TITLE
Guess: Can't guess all blanks

### ISSUE THREAD

**Issue by BWPanda** [chrisboyle/sgtpuzzles#469]
In a game with 'allow blanks' turned on, you can't submit a guess consisting entirely of blanks (the dots on the right don't light up blue, so you can't submit your guess).

**Comment by chrisboyle** [comment]
The help for "Allow blanks" says (note second line in particular):

> Allows blank pegs to be given as part of a guess (makes it easier, because you know that those will never be counted as part of the solution). This is turned off by default.
> Note that this doesn't allow blank pegs in the solution; if you really wanted that, use one extra colour.

For this reason, it would not make sense to submit an entirely blank guess (none of them would be correct).

**Comment by BWPanda** [comment]
Oooh, OK. Sorry, missed that :-)
