### ISSUE TITLE
Fdroid's packaging introduces Anti-features

### ISSUE THREAD

**Issue by etanot** [chrisboyle/sgtpuzzles#470]
Fdroid shows this app contains some anti-features 
  * This app has a weak security signature
  * This app contains a known security vulnerability

Is there a way to fix these?

**Comment by chrisboyle** [comment]
@finn0 I can't find any such warnings on f-droid.org or in the F-Droid app (but I do already have Puzzles installed of course). Can you attach a screenshot? Do they link to a page explaining what they mean?

**Comment by finn0** [comment]
@chrisboyle Here,

App name: Puzzles
App version: 2018-10-27-1350-f281644b
FDroid app version: 1.6

>  Can you attach a screenshot? 

![puzzles](https://user-images.githubusercontent.com/28824347/56630192-0fc4b300-6640-11e9-85a5-99cabdcac630.jpg)


![anit-feature](https://user-images.githubusercontent.com/28824347/56630186-0affff00-6640-11e9-8b93-abb3354c01b2.jpg)

> Do they link to a page explaining what they mean?    

Issues:   
* [This app has a weak security signature](https://f-droid.org/wiki/page/Antifeature:KnownVuln)
* [This app contains a known security vulnerability](https://f-droid.org/wiki/page/Antifeature:DisabledAlgorithm)

**Comment by JonnyTech** [comment]
Links:
https://f-droid.org/wiki/page/Antifeature:KnownVuln
https://f-droid.org/wiki/page/Antifeature:DisabledAlgorithm

**Comment by chrisboyle** [comment]
Ok, those are both to do with how the app is built and signed, i.e. to do with F-Droid's build process. I say that because there's nothing in the source code here that requests old signing algorithms. This is really a job for whoever is maintaining the F-droid build of Puzzles, or in any case someone more familiar with how F-droid builds work.

**Comment by chrisboyle** [comment]
Looking at the F-Droid app on my phone, and on https://f-droid.org/en/packages/name.boyle.chris.sgtpuzzles/ , I currently see no such warnings for Puzzles, even if it's uninstalled. Closing this, reopen if you see the warnings again.
