### ISSUE TITLE
Mines - swap press and long press actions

### ISSUE THREAD

**Issue by mmm4m5m** [chrisboyle/sgtpuzzles#472]
Currently, long press mark the field with flag. If you do mistake and press short time then you die. 

Swap both actions will be better.

Thanks.

**Comment by chrisboyle** [comment]
Thanks for your report. Button swapping is already available for all games: press the ". / -" button at the bottom. It will be remembered for each backend (so, for all Mines games).

I don't want to swap by default just for Android, as it would be inconsistent with the long-established behaviour on other platforms.
