### ISSUE TITLE
every game says Game generation exited with status 1

### ISSUE THREAD

**Issue by mrducky4** [chrisboyle/sgtpuzzles#487]
I used this game often with no problem on chromebook. I hadn't used it for a while, and now every game gives the error: Game generation exited with status 1.
Chrome OS Version 89.0.4389.95 (Official Build) (32-bit)
Is there anything I can try, to get it working again?

**Comment by chrisboyle** [comment]
This suggests that the game generation executable is missing. Some people have got into that situation by using third-party backup/restore tools that make certain assumptions about file layout, but I don't imagine you've used anything like that on a Chromebook? Try reinstalling the app anyway, that should get you a fresh copy of the executable.

**Comment by mrducky4** [comment]
Thanks. I uninstalled, reinstalled, and it is working again. I can't think of anything that might have triggered this problem.
