### ISSUE TITLE
New: Mosaic puzzle

### ISSUE THREAD

**Issue by tmp6154** [chrisboyle/sgtpuzzles#488]
A new puzzle has been committed into sgt-puzzles collection and it would be great if it could be added into Android port as well (might be a good time to merge changes, since other puzzles has also accumulated quite a lot of changes and fixes since last Android port update).

**Comment by chrisboyle** [comment]
This is now merged and ready for the next release (it might just need a tweak to night mode colours).

**Comment by chrisboyle** [comment]
I've sorted out the keyboard in 0de2ffee06df8922cfe8eb4a1bd331a2b63d7bc7, split the night mode colours thought to #519, and this is otherwise ready (at least for beta).
