### ISSUE TITLE
Feature request - A change to navigation bar

### ISSUE THREAD

**Issue by cartler-ctrl** [chrisboyle/sgtpuzzles#490]
The navigation/action bar at the bottom of screen takes up precious space. And for people like me, it is a blinding white against the black background. An option to make the bar black would be nice.

**Comment by chrisboyle** [comment]
In today's beta release, the bar (if enabled in system settings) appears black on at least Pixel 6 Pro and OnePlus 5T. The change most likely to have caused this is probably the upgrade from Android Support Library to AndroidX. If anyone has a burning desire for Puzzles to do anything different with the system navigation bar, and some idea of where in the Android API it can be done, then please do reopen.
