### ISSUE TITLE
Dominosa: Highlight number keys

### ISSUE THREAD

**Issue by goyalyashpal** [chrisboyle/sgtpuzzles#502]
In the dominosa game, ([Art 17.1 Dominosa Controls](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/dominosa.html#dominosa-controls))
> Pressing a number _key_ will highlight all _occurrences_ of that number.

The suggestion is to highlight the pressed/active number keys too. This will be small but good quality of life improvement.

Current: (button for 2 is not highlighted)

![image](https://user-images.githubusercontent.com/19423063/162483775-48371a83-3bb7-4ea1-8a48-242d73085ada.png)

duplicate search: 🔍 [dominosa key highlight](https://github.com/chrisboyle/sgtpuzzles/issues?q=is:issue+dominosa+key+highlight)

**Comment by yashpalgoyal1304** [comment]
related: https://github.com/chrisboyle/sgtpuzzles/issues/417
