### ISSUE TITLE
Black Box: highlight corresponding (exit's) edge clue

### ISSUE THREAD

**Issue by goyalyashpal** [chrisboyle/sgtpuzzles#509]
### Summary:
On left tapping, the edge clue for corresponding exit is not highlighted similar to how it does in the web version

#### Steps:
1. in Black Box game, click on edges to reveal the clues
2. when some numeric clue appears, then single click it
3. now click and hold it

#### What happened:
* after 2: nothing
* after 3: interpretted as "right click" - hence, locks the entity (R or C)

#### What should have happened:
i dont have a clear opinion.
* to me: click and hold should match what web version does here, that is, highlight the corresponding clue. 'cz it doesnt seem to be have any alternate suitable actions. Right click on the other hand HAS very reasonable alternate action already available - toggling via that button in bottom bar.
* but click and hold does right click throughout _most_ of this android app framework, and making an(other) exception may be unwelcome by some.

---
### References:
* doc ref: Ch 19.1 [blackbox.html#blackbox-controls]
* game's web version: [web version🡭]
* screencapture

https://user-images.githubusercontent.com/19423063/137795780-e01f184f-69ae-4175-b42f-2e5f7d1b6a55.mp4

 ### Versions:
* Puzzles app: 2019-03-26-0844-68363231
* web: "(last modified on Tue Sep 14 01:48:08 2021)" 
_(wow, what a format `DDD MMM dd hh:mm:ss yyyy` 😅)_
* android: any

[web version🡭]: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/blackbox.html
[blackbox.html#blackbox-controls]: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/blackbox.html#blackbox-controls

---
* duplicate 🔍 : [highlight edge clues]https://github.com/chrisboyle/sgtpuzzles/issues?q=highlight+edge+clues)
* issue template from: inkscape's issue template

**Comment by yashpalgoyal1304** [comment]
saying before hand: i would be slightly against having this idea extended to show the complete light path - let there be some easy mental work too ;)
