### ISSUE TITLE
Monospace content in help shown in variable width on some devices

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#512]
Tepi-Liz Hatfield writes:
> App: Simon Tatham's Puzzles
> Game: Black Box
> Platform: Android 9
> Device: Samsung Galaxy S8+
> Issue: The text alignment for the ASCII layouts in the rules to "Black Box" displays in a variable-width font rather than fixed-width, so the grid appears essentially unintelligible on the screen.*

The grids do appear fixed-width for me - perhaps it's doing so using a font that isn't universally available, or there's some quirk to HTML rendering on that device?

**Comment by yashpalgoyal1304** [comment]
hi @ Tepi-Liz Hatfield, 
1. can u please attach the screenshot of the issue? 
2. And as you are using a samsung device, i would assume that you are using a custom font (in theming or some such). 
Can u share the name of the font used as well??
3. If you are willing to do so, then after doing both above, can u try changing the font to a default one? 
(default - i mean the one used generally in android, though i dont know what that is 😅 )

**Comment by chrisboyle** [comment]
Never got any further info nor any other reports, so closing this. Reopen if seen.
