### ISSUE TITLE
Solo: 3x1 Basic generation spins forever

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#520]
**Describe the bug**
Trying to generate a game with sub-blocks columns 3 and rows 1 (i.e. Jigsaw 3) and Basic difficulty will just spin forever, both on Android and upstream.

**To Reproduce**
1. Go to Solo -> Type -> Custom.
2. Set rows to 3, columns to 1, difficulty to Basic or higher, and hit OK.
4. See "Generating game" forever (or on Linux it just hangs).

**Expected behavior**
Either a generated game or an error that this size/difficulty combination is not possible.

**Comment by mquevill** [comment]
I submitted an upstream pull request relating to this. (Commit here: https://github.com/mquevill/puzzles/commit/5c9a7b64a06d07f97a41622c4b91d81f3419a51b)

**Comment by bjh21** [comment]
Committed upstream as 11c1447eac7698f01c2a00764c2b1a900a9d6a90 (https://git.tartarus.org/?p=simon/puzzles.git;a=commitdiff;h=11c1447eac7698f01c2a00764c2b1a900a9d6a90).
