### ISSUE TITLE
Integrate with "Dark theme" on Android 10+

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#530]
We have a Night mode, which by default is activated based on light level, or can be forced on or off in app settings. Now the OS has a dark theme ([dev guide](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme)), I think this would be another possible mode for the setting, so you have:

**Night mode**
* On
* In low light (current default)
* Off
* When system dark theme is on

Arguably this new mode could become the default for new installations, and I might be able to detect that the user has never changed the setting, in which case I could decide to apply it in that case too?

**Comment by mquevill** [comment]
Phrasing it as "Follow system settings" or "System default" would probably be more consistent with other apps.

I think it would be a good default setting, especially if you can migrate over whether users have/haven't changed that setting. It should be easy enough for the user to force it to whatever they want. (This app is one of the few I leave in light mode.)

**Comment by chrisboyle** [comment]
A quick experiment suggests the preference is written if you've ever opened the settings screen, even if you didn't touch night mode, i.e. there's no way to distinguish users who have changed the preference. :frowning_face: I'm therefore thinking of making "Follow system" the default for **new installations only**, but leaving any existing value alone (at the technical level: declare it as the default, but don't write any attempt at migration code).

Anyone who's ever opened the app in a low-light environment will know that night mode exists, and it's fairly prominent in the settings screen if they do want to change it. It'll also be mentioned in the "What's new" in Google Play. I think changing the preference out from under people would just unnecessarily annoy people who like the current behaviour, whether they explicitly chose it or not.
