### ISSUE TITLE
Autofollow in Loopy

### ISSUE THREAD

**Issue by mquevill** [chrisboyle/sgtpuzzles#550]
There is a somewhat hidden option for Loopy in the upstream source code. On the desktop version, I have set an environment variable (`LOOPY_AUTOFOLLOW="adaptive"`). As someone who uses this option on the desktop version, it would be great to have it in this app.

I'm thinking it would be as simple as adding an option that sets this variable internally, since the code structure is all there.

https://github.com/chrisboyle/sgtpuzzles/blob/3ae4a036d8ef888154ff8419ca2a441f4826fde9/app/src/main/jni/loopy.c#L3139-L3151

**Comment by yashpalgoyal1304** [comment]
hi, what does this autoflow does? a little summay here will help

**Comment by chrisboyle** [comment]
Good news: upstream's new settings framework means that the next Android release will have this available on the settings screen.
