### ISSUE TITLE
Remove circle from app icon on old Android

### ISSUE THREAD

**Issue by nanderer** [chrisboyle/sgtpuzzles#552]
hi,

i just updated to the latest fdroid version Version 2022-04-30-1100-c43a34fb-fdroid on my android 8 device and was not very happy witch how you handle the app icon on my device. i know that on android 10 good old transparent icons will be displayed badly with a forced white background but just forcing a blue circle 🔵 behind the nice squarish icon without changing it into a new one lookes quite bad on my device where other apps still have there not forced old style icons.

maybe you could find a way to use the old icon style on devices with an android that dose still support nice transparent icons and only do what youve done on devices that have this terrible non transparent new style icons...

thanks in advance and keep up the good work

**Comment by lufebe16** [comment]
The new icons are too colorful and no longer fit into the otherwise simple design of this app. Please bring back the old icons or if it is a matter of adapting to a newer android version: find a solution which fits to the look and feel of the former version.

**Comment by chrisboyle** [comment]
I've had no other complaints about the app icon since this change, and according to https://apilevels.com/ 84% of devices are now on Android 10 or higher, so 16% (and decreasing) would see any benefit here, so unfortunately it's not something I can find time for.
