### ISSUE TITLE
Time signpost

### ISSUE THREAD

**Issue by Proxtx** [chrisboyle/sgtpuzzles#558]
**Additional context**
A final time after finishing the puzzle. Basically just like mines would be great. The timer should start as soon as you generate the level.

Thanks in advance.
Discovered Signpost through this collection and I'm in love with it.

**Comment by adlai** [comment]
There's no chance this would be as simple as flipping the `game.is_timed` boolean, right?

**Comment by chrisboyle** [comment]
This is a special case of #324 and should be discussed there.
