### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by jjbali** [chrisboyle/sgtpuzzles#565]
make a daily levels with unique seed, a puzzle editor, and a floating game window

**Comment by chrisboyle** [comment]
Hi, thanks for your suggestions, but I'm not sure any of them are a good fit for this project:

* Daily levels could mean a few different things:
  * Some other apps have a daily level that appears the same for everyone, which realistically starts down the road of having a server, which would require funding, and that would conflict with this project's goals of remaining completely free, never showing ads, and being fully usable offline.
  * Even if the app just generates a random level on the device (which would be different for everyone), I'm not sure what the advantage would be compared to just going into the app and tapping New Game on your favourite game. I certainly don't want daily notifications nagging people to use the app. Reviewers frequently thank me specifically for not doing that sort of thing, and if you do want that, it's simple enough to make for yourself using e.g. Tasker.
* Editors: I think a few games do have undocumented editors in the source code in various stages of completion, but this is really something that should be addressed/completed upstream first. By "upstream" I mean that this project is actually a port; Simon Tatham still maintains [the original collection](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/) for other platforms and I try to remain consistent with that, so it should be discussed with him. He doesn't have a bug tracker for it but there's a feedback section at the bottom of that link.
  * As a workaround: tap the game size button, select Custom, then Game ID: you'll find that parts of that ID directly correspond to the board layout and you can often edit the string to encode the board you want.
* A floating game window is theoretically possible, but I'd suggest thinking about what it would actually be like to try to use some of these games at the size of a typical floating window, when some of them are already tricky to interact with on the whole screen. What you can already do is use split-screen on recent versions of Android: open Puzzles, open a different app, swipe up (or press your recent-apps button), and above Puzzles' screenshot there should be an icon. Tap that and there should be an option to split the screen into two apps. Or use a ChromeOS device: Puzzles will open there in a resizeable window already. I think some larger tablets may also offer a similar resizeable window feature for all apps as part of their version of Android (mine doesn't).

Sorry not to be more help, do open another issue if you have a different idea, but also please try to keep to one idea per issue.

**Comment by jjbali** [comment]
Trying to refer at the game [Shattered Pixel Dungeon](https://github.com/00-Evan/shattered-pixel-dungeon) by [00-Evan](https://github.com/00-Evan) to use a separate seed to make a "daily" like games even the game has infinite possibilities because it is generated.
