### ISSUE TITLE
Galaxies: multiple valid solutions didn't validate

### ISSUE THREAD

**Issue by alanvoss** [chrisboyle/sgtpuzzles#569]
**Describe the bug**
Multiple valid, rotationally symmetrical solutions didn't validate.

**Expected behavior**
These should have validated as solutions, but didn't.

I didn't unfortunately take a screenshot of the solution, but it was to remove 2 lines in each of my submitted sitting and make the shape completely continuous.

**Screenshots**
![Screenshot_20221016-095314_Puzzles](https://user-images.githubusercontent.com/1993821/196043000-a42a1d37-afcd-43c9-b24f-8afcf0ed514a.jpg)
![Screenshot_20221016-095403_Puzzles](https://user-images.githubusercontent.com/1993821/196043002-c0ec9b58-ddda-47ee-95a9-a62ece3a5083.jpg)

**Version info (optional, but sometimes helpful)**
Version 2022-05-21-1809-c43a34fb
Android 12
Galaxy S22 Ultra

**Additional context**
I love these games and I think it is an awesome collection!

**Comment by xlenstra** [comment]
According to the rules:

The puzzle is complete when the marked lines on the grid are precisely
those that separate two squares belonging to different regions.

Thus, your solution doesnt follow the rules and the fact that it isn't
accepted isnt a bug.
