### ISSUE TITLE
Add a stopwatch that stops when you solve the puzzle

### ISSUE THREAD

**Issue by R1Vv** [chrisboyle/sgtpuzzles#576]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. A stopwatch, that you can optionally turn on, that when you solve the puzzle, stops, and is shown to you.

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisboyle** [comment]
Duplicate of #324
