### ISSUE TITLE
All games request

### ISSUE THREAD

**Issue by SherylK621** [chrisboyle/sgtpuzzles#579]
I would prefer not to have errors turn red on all games until I'm done solving. For example, in Slant, I don't switch between left and right slant, I toggle thru to the one I want. I'd rather not know which is wrong until I'm ready to know. 

A 'show errors' feature would work here.

**Comment by chrisboyle** [comment]
Thanks for your suggestion. This is a duplicate of #258 (and would need to be coordinated with Simon upstream; it's not something I would want as an Android-specific difference).

**Comment by SherylK621** [comment]
Got it - thanks Chris.
