### ISSUE TITLE
Can't open "Mosaic"

### ISSUE THREAD

**Issue by saidelmark** [chrisboyle/sgtpuzzles#582]
**Describe the bug**
After latest update I can't open "Mosaic" puzzle, while all the others are just fine.

**To Reproduce**
1. On the previous version of the app play "Mosaic" and leave an unfinished game
2. Update the app
3. Open "Mosaic"

At least that was how I got this. Maybe the reason is that I used a custom field size, buy other games don't have such problem.

**Screenshots**
![Screenshot_2023-01-17-23-48-19-71_57594183e98acbd5c528e733d62aa74f.jpg](https://user-images.githubusercontent.com/9284083/212998117-b1216a18-d467-4281-8383-00b2a088b792.jpg)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: OnePlus 8T
 - Android version: 13
 - App version: 2023-01-15-2303-5782e29d

**Comment by chrisboyle** [comment]
Thanks for your report; I've found the problem (introduced with the recent security updates) and I'll push another update soon. Google Play will probably take a couple of days to distribute it. Meanwhile if you want to play Mosaic you could downgrade to the [previous release](https://github.com/chrisboyle/sgtpuzzles/releases/tag/2022-05-21-1809-c43a34fb). As far as I know the security issues are only relevant when handling saved game files, so don't open any of those from untrusted sources and you should be fine.

**Comment by chrisboyle** [comment]
Leaving this open for visibility until the update is available, otherwise we'll get a lot of duplicates.

**Comment by saidelmark** [comment]
Confirming: after the unload everything works. Thanks! That was really fast 🙂

**Comment by KingisNitro** [comment]
Hey, I had the same issue, glad to see it resolved. Interestingly, with reinstallation of the app through Play Store, only certain sizes didn't work (likely those where I had a saved game). 
Downloading and installing the apk from the new update makes everything work, thank you very much. 👍❤️

**Comment by yenseo7009** [comment]
Me too

**Comment by ilp1968** [comment]
Same problem here, however someone was faster than me. Thanks @saidelmark  for reporting. And thanks a bunch @chrisboyle for the quick fix, will wait for an update now. I'm still at Version 2023-01-15-2303-5782e29d. Let me add a big thank you for upping to the Android 13 APIs, legibility improved a lot for many games!

**Comment by chrisboyle** [comment]
Closing now that the fix has been out for a while.
