### ISSUE TITLE
Show Best Times For Puzzles

### ISSUE THREAD

**Issue by Toonwoons** [chrisboyle/sgtpuzzles#587]
I've been getting really good at some of these puzzles, and I think it would be a fun feature to show your fastest time completing each difficulty in each game.

Not everyone will care about their best time, so it should be an on/off toggle in the settings. My idea is to start a hidden (or shown) timer on game generation, and record the fastest time in the drop-down box for difficulty, like in the screenshot. Alternatively, it could go in the corner.

![Screenshot_20230121-200111](https://user-images.githubusercontent.com/123278316/213896083-d53571a2-3751-4dca-ae56-0d80e72de12e.png)

**Comment by chrisboyle** [comment]
I just noticed we already have #324 for this so let's track it there.
