### ISSUE TITLE
Train tracks: columns selected from below

### ISSUE THREAD

**Issue by Cydonya** [chrisboyle/sgtpuzzles#588]
**Describe the bug**
When playing Train Tracks, sometimes if you touch the blank area below a random column, it will select some tiles or the entire column above (grey, crossed or deleted).

**To Reproduce**
1. Go to 'Train Tracks'
2. Play the game for a while
3. Touch around the blank area below the grid
4. Eventually you will see some tiles or an entire column selected
5. not reproduceable every time

**Expected behavior**
No tiles should be selected touching the blank area below the grid, as this accidentally adds unwanted moves to the game.

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: galaxy a20e
 - Android version: 11
 - App Version 2023-01-18-2324-aaa36328

**Comment by sprickett** [comment]
To reliably reproduce:

* Drag finger along row or column selecting at least two squares.
* Before lifting finger, move to an adjacent row / column discarding the selection
*  Tap screen above or below board in line with the first touch of the drag. 

Squares between first touch and tap become marked.

It does not matter if initiated by a long or short tap

Version 2023-01-18-2324-aaa36328 (not new behaviour)

**Comment by chrisboyle** [comment]
The update to fix this is now available in Google Play. Thank you both for your reports :-)

**Comment by sprickett** [comment]
Thank you for the speedy fix and for your time and I assume money for
handling the Android port
