### ISSUE TITLE
Undo action performed when leaving app

### ISSUE THREAD

**Issue by JonnyTech** [chrisboyle/sgtpuzzles#592]
**Describe the bug**
When one switches away from the app, or closes it, then restarts it, the last move has been undone.

**To Reproduce**
1. Start bridges
2. Link some islands
3. Swipe up to recents switcher
4. Notice the last move missing
5. Switch back to app
6. Swipe up again
7. Another undo action performed
8. Repeat
9. More moves undone

**Expected behavior**
The last game state to be remembered and preserved when leaving the app.

**Screenshots**
Make some moves:
![Screenshot_20230220-111012_Trebuchet](https://user-images.githubusercontent.com/3584732/220090524-e5e0e32d-647a-4ddc-93e3-7eff5990827e.png)
Swipe up:
![Screenshot_20230220-111034_Puzzles](https://user-images.githubusercontent.com/3584732/220090550-ad8a46cc-69bf-4f4f-bc9f-ee8d861ec71f.png)
Where did that last line go to?

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: OnePlus
 - Android version: 13 (LineageOS 20)
 - App version: Version 2023-02-10-1537-bd5c0a37-fdroid

**Additional context**
This may simply be a consequence of having system gestures enabled.

**Comment by JupiLogy** [comment]
I've tested this in my own phone (OnePlus as well, but Android 12). On mine, it works as expected.

**Comment by JonnyTech** [comment]
Update: the issue is not present with 3 button navigation, but does manifest with gesture navigation and 2 button navigation (which also uses swipe up gestures)

![Screenshot_20230220-113314_Trebuchet](https://user-images.githubusercontent.com/3584732/220095597-29a25ea9-370d-4b11-95e0-8bf71e575a2f.png)

**Comment by JonnyTech** [comment]
> I've tested this in my own phone (OnePlus as well, but Android 12). On mine, it works as expected.

@JupiLogy thanks for testing, this may ba a specific Android 13 issue but I have no other devies to check.

**Comment by chrisboyle** [comment]
Reproduced on Pixel 6 Pro with Android 13. I have a thin grey bar added by the system (see screenshot) and I think I normally start my gestures from the very edge of the screen or within that area. By starting my swipe a few pixels further up, within the application area and such that it crosses the undo button, I get the behaviour described. This is probably very common especially among people who use cases on their phones, and needs fixing.

The broader issue here is it looks like all the keyboard buttons will take action if a swipe crosses them, whereas the intention was only to act if the touch is contained within a single key from start to finish (and perhaps constrained more tightly than that according to any Android standard touch parameters). Relatedly, we are relying on deprecated platform keyboard classes (see #532) which don't have an `androidx` replacement as far as I know, so it's probably time to fix that too by implementing our own keyboard view that behaves sensibly, or adding a dependency if a **very small** and permissively-licensed one exists.

![home-bar](https://user-images.githubusercontent.com/127305/220100641-7d6e8bad-6da5-49a2-a5bc-3394f9cce07c.png)

**Comment by JonnyTech** [comment]
Thanks for confirming @chrisboyle, havivg a case or not swiping from the very bottom is not the issue, it seems that disabling the navigation hint (thin line at bottom) is the cause:

![IMG_20230220_122146](https://user-images.githubusercontent.com/3584732/220106686-c2484c49-c335-4801-805a-b9bf2d1c056e.jpg)

At least I have a workaround for now, I appreciate you looking into this.

**Comment by goyalyashpal** [comment]
> so it's probably time to fix that too by implementing our own keyboard view that behaves sensibly, or adding a dependency if a **very small** and permissively-licensed one exists.

is keyboard view same as keyboard?

if yes, then [rkkr/simple-keyboard] might be the one. Apache-V2 0.8 MiB in setup (apk) size.

[rkkr/simple-keyboard]: https://github.com/rkkr/simple-keyboard

**Comment by goyalyashpal** [comment]
> Apache-licensed like the rest of Android, whereas I don't want to change this project's licence away from MIT (same as upstream).

FutharkBoard (Elder Futhark keyboard for Android) - https://f-droid.org/app/de.drmaxnix.futharkboard

Irregular Expressions (Virtual keyboard for writing expressive messages in various text styles) - https://f-droid.org/app/mf.asciitext.lite

these are lnly 2 i could find in officual fdroid repo with MIT licence. there were others with unlicence or bsd-3, but i dont onow if they are compTible with mit-l.

**Comment by chrisboyle** [comment]
Thank you for finding these, but unfortunately they both just import the deprecated KeyboardView from the OS i.e. they do what Puzzles does now that I'm trying to change - [Futhark here](https://github.com/DrMaxNix/futharkboard/blob/main/android-app/app/src/main/java/de/drmaxnix/futharkboard/IME.java) and [Irregular here](https://github.com/MobileFirstLLC/irregular-expressions/blob/master/base/src/main/java/mf/irregex/keyboard/IrregularKeyboardView.kt)). Looks like I'll have to write my own View for it then.
