### ISSUE TITLE
NEW: Sumplete

### ISSUE THREAD

**Issue by goyalyashpal** [chrisboyle/sgtpuzzles#594]
> Delete numbers so each row/column adds up to target numsber at borders

ref:
- https://github.com/cyb3rko/pincredible/issues/19
- https://sumplete.com

**Comment by goyalyashpal** [comment]
i just wanted to share this idea here, don't really want the game or anyth. so, closing from mybside. Feel free to reopen or upvote for it.

**Comment by JonnyTech** [comment]
You should submit this upstream, directly to Simon.
