### ISSUE TITLE
Hat tiling for Loopy

### ISSUE THREAD

**Issue by bmreiniger** [chrisboyle/sgtpuzzles#599]
Tatham has added a new tiling for Loopy, based on the recently discovered aperiodic monotile nicknamed the Hat.

https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/loopy.html#10x10t16
https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/aperiodic-tilings/
https://git.tartarus.org/?p=simon/puzzles.git;a=commit;h=6fb890e0ea20a3c366ffd2de45d26a0c1c454dd6

**Comment by ostrosablin** [comment]
Even more fun, same authors, who have discovered the original Hat tiling have refined the shape, so there's a new Spectre tiling which is closely related to predecessor.

What makes it more interesting than Hat tiling is that it no longer requires mirrored copies of the original shape to tile aperiodically, so now it can be considered a true solution to the einstein problem (without mirrored shapes which could be considered two separate tiles). This makes the tiling even more elegant and mathematically beautiful.

Simon has already added Spectre tiling to latest master.

**Comment by ostrosablin** [comment]
Somewhat related, Simon has re-made Penrose tiling generator, using similar aperiodic tiling algorithm to one he had devised for Hat/Spectre tilings.

https://git.tartarus.org/?p=simon/puzzles.git;a=commit;h=61e9c782487ea982498955b93d1b94921131059e
