### ISSUE TITLE
Settings for the completion animation

### ISSUE THREAD

**Issue by divi0001** [chrisboyle/sgtpuzzles#601]
When solving something like bridges or untangle or bulb, at the end of the game, when you beat it, the screen flashes white and dark in quick succession, I am requesting to have a setting to turn this off, or have another animation, for a multitude of reasons:
1. This might cause epileptic people to have an attack
2. It scares me lol
3. It looks from outside as if you are making photos

**Comment by chrisboyle** [comment]
Have a look at Settings -> Display and input -> Animations... does that do what you're looking for?

**Comment by divi0001** [comment]
Oops sorry, my bad
