### ISSUE TITLE
A puzzle with two solutions in Solo?

### ISSUE THREAD

**Issue by baruchel** [chrisboyle/sgtpuzzles#608]
**Describe the bug**
Encountered a Solo puzzle which seems to have two equivalent solutions.

**Screenshots**
![Screenshot_20230623-134312](https://github.com/chrisboyle/sgtpuzzles/assets/6763978/84b694d8-5a5e-4875-a830-d035d55a6441)

**Version info (optional, but sometimes helpful)**
 - App version 2023-02-10-1537-bd5c0a37

**Comment by chrisboyle** [comment]
@baruchel Thanks for your report; I can't immediately see why either solution would be invalid...

- Please save the game to a file and share it, or at least the game ID
- Was this definitely generated by the app and not loaded as an ID or file from elsewhere?
- Are you able to enter either combination of digits and do they both result in the "completed" popup and no error indications?

Thanks

**Comment by SteffenBauer** [comment]
I think the solution is unique.
A often overlooked rule for the 'killer' type from the documentation (https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/solo.html#solo):

> Also, no digit may appear more than once within a cage, even if the cage crosses the boundaries of existing regions.

The bended 3-cell box in the lower right applies here. To fill this with 8-1-8 would satisfy the sum 17, but violated above rule. So Only a '4' can be filled in the top cell of this 3-cell box. The rest of the puzzle should then be unique.

**Comment by chrisboyle** [comment]
Thanks @SteffenBauer , that makes sense of it
