### ISSUE TITLE
Solo: show pencil marks in 3x3 grid in cell

### ISSUE THREAD

**Issue by erikhuizinga** [chrisboyle/sgtpuzzles#611]
Solo pencil marks in a cell are shown in numerical order, e.g.:

```
1 2 4
5 9
```

This is ok, but not great, as pencil marks can be used to spot patterns. Spatial cues may help here. Therefore, with paper and pencil, I do the following for which I make this suggestion:

I'd like an option (or maybe default) to show Solo pencil marks in a single cell on a 3x3 grid, e.g.;

```
1 2
4 5
    9
```

(Same numbers as example above.)

For reference, the whole grid is:

```
1 2 3
4 5 6
7 8 9
```

(Ironically, this is already how a cell with all pencil marks is rendered.)

I've looked in the settings and haven't found something like this. Please let me know if this is already possible, and otherwise please consider this issue.

**Comment by chrisboyle** [comment]
Hi, thanks for the suggestion. I think open issue #260 covers this, so closing as duplicate.

**Comment by erikhuizinga** [comment]
You're right that that issue includes what I describe. You could consider splitting the other issue up in multiple smaller ones, unless they're closely related or tightly coupled. Thanks for considering this.
