### ISSUE TITLE
Tents number bug

### ISSUE THREAD

**Issue by FJonyAguilar** [chrisboyle/sgtpuzzles#613]
**Describe the bug**
An extremely rare error ocurred on my "tent" Game: the last file number is "6" , but when you see the solution they're actually 5 tents and the game dont recognize it as a error.

**To Reproduce**
1. Go to tents Seed Version 2023-02-10-1537-bd5c0a37
2. Try yo complete the game from last file (or see solution)
3. You will see the error

**Expected behavior**
6 tent tiled on last file

**Screenshots**
![Screenshot_20230810-071049](https://github.com/chrisboyle/sgtpuzzles/assets/124702866/7ab28065-6b95-4078-9e79-0cbed7beada6)

**Comment by chrisboyle** [comment]
I think you may have zoomed in: the left edge of the screenshot looks like there might be another column off that edge, which could include another tent there

**Comment by JupiLogy** [comment]
I agree with Chris, it looks like you're zoomed in so that the whole puzzle is not visible.

**Comment by FJonyAguilar** [comment]
omg i cant believe it, thats why you shouldn´t play in movile device
