### ISSUE TITLE
Keen etc.: add toast when resetting pencil marks

### ISSUE THREAD

**Issue by homerggg** [chrisboyle/sgtpuzzles#614]
**Is your feature request related to a problem? Please describe.**

It's frustrating when you're almost done with a Keen puzzle and you press the Pencil Marks button thinking it allow you to switch between pencil and filled-in numbers and Poof you've lost every pencil mark (in essence you need to restart).

**Describe the solution you'd like*
If pencil marks has been added/removed, add a confirmation dialog stating that you will lose every pencil marks (Are you sure ?).

**Describe alternatives you've considered**
Change the behavior of that button so that it does not reset pencil marks.

Change the behavior of that button so that it allow to switch between pencil marking and filled-in numbers.

**Comment by chrisboyle** [comment]
Hi, thanks for your report. The pencil-marks button counts as a move, so the Undo button will let you undo it (if you pressed pencil-marks multiple times then you must undo the same number of times).

There's already a setting on the Settings screen to hide the pencil-marks button, but maybe there could also be a Toast when you press pencil-marks, pointing out the Undo button. I think a confirmation dialog would be the wrong solution given that undo already exists.

**Comment by homerggg** [comment]
It didn't occur to me that the undo button would work for that action. Frustration at the time it happen obscured my judgment ! A toast pointing the undo button would probably have saved me the frustration. Thanks!
