### ISSUE TITLE
Media playback interrupts

### ISSUE THREAD

**Issue by saidelmark** [chrisboyle/sgtpuzzles#615]
**Bug description**
Whenever I open (or close) Puzzles, the music gets muted for a second or two. I tried some music apps, and this behavior persists. Didn't try with YouTube premium, don't have it.

**To Reproduce**
1. Start listening to music
2. Open Puzzles to casually solve something
3. The music kinda chokes for about a second

You can replace step 2 with "Switch from Puzzles to another app", then the interruption will not be immediate, it'll come 2–3 seconds later.

**Expected behavior**
I expect puzzles to not interfere with media playback

**Version info**
 - Phone/tablet model: OnePlus 8t
 - Android version: 13 (OxygenOS 13.1)
 - App version 2023-02-10-1537-bd5c0a37

**Additional context**
I ran some experiments and didn't find any other app I use that would have the same issue.

**Comment by chrisboyle** [comment]
Hi, thanks for your report. Puzzles certainly doesn't intentionally interact with sound or media playback at all. As nobody else has mentioned any issues with this, from what Play tells me is ~148K active devices, it is probably specific to your device unfortunately.

**Comment by saidelmark** [comment]
Looks like you're right, and it's some kind of "Gaming mode" provided by the device manufacturer.
