### ISSUE TITLE
Net: valid solution not recognised

### ISSUE THREAD

**Issue by fmacdude** [chrisboyle/sgtpuzzles#618]
See screenshot. Some terminals do not light up even though connected to server. The "disconnection" seems to occur when warping from one side of the board to the other. However, on the same board, this works with other connections that warp from one side of the board to the other.

Saved game attached.

 - Phone/tablet model: redmi note 10 pro
 - Android version: 12
 - App version: 2023-02-10-1537-bd5c0a37-fdroid
 
![Screenshot_20230930-175539_Puzzles](https://github.com/chrisboyle/sgtpuzzles/assets/146534425/840db109-fc48-4121-a9c8-2ef200655076)

**Comment by fmacdude** [comment]
(I have the saved game file, but can't figure out how to attach here)

**Comment by chrisboyle** [comment]
Hi, thanks for your report. Based on the red outline, this is not a wrapping board. If you look in the Type menu (resize-ish icon near top right) you'll see some options have wrapping and some don't. If you've chosen a custom game, then press Custom again and you'll see the current state, including the checkbox for whether wrapping is allowed or not. The screenshot above looks consistent to me: everything that's lit up has a path to the centre without crossing the outside edge.

**Comment by chrisboyle** [comment]
(for future reference if you need to attach a file on Github, you can click on the the "Attach files..." message just below the comment box - or, on desktop platforms, drag and drop)

**Comment by fmacdude** [comment]
Thank you, you are correct
