### ISSUE TITLE
Click mailto link crashes the app

### ISSUE THREAD

**Issue by littlecd** [chrisboyle/sgtpuzzles#626]
In HelpActivity, click an email link crashes the app.

![pic13](https://github.com/chrisboyle/sgtpuzzles/assets/144590216/6e03bab0-9a1d-4912-9ffd-7f06e9418c03)
click anakin@pobox.com

![pic14](https://github.com/chrisboyle/sgtpuzzles/assets/144590216/b2578912-aefa-4762-aa7a-195c529c7073)

**Comment by chrisboyle** [comment]
Hi, thanks for your report. I'm guessing you don't have any email app installed? I should of course handle this better (catch `ActivityNotFoundException`) but just to confirm, can you open your browser and click an email link? You can find one right at the bottom of https://www.chiark.greenend.org.uk/~sgtatham/puzzles/ - and confirm that the browser shows a brief message (Toast) saying that there's no suitable application installed, which is what I should do in Puzzles.

**Comment by littlecd** [comment]
Hi, thanks for your reply. Yes, I can confirm there is a toast saying "Unable to open this type of link" when I use DuckDuckGo to open the link.
