### ISSUE TITLE
Let us keep the cursor after definite marks

### ISSUE THREAD

**Issue by Cigaes** [chrisboyle/sgtpuzzles#628]
Hi.

In a recent change, when playing on touchscreen, the cursor disappears just after we make a definite mark. This is intentional, as there is an option to “keep cursor after changing pencil marks”, but it only applies to pencil (blue) marks, not definite (green) ones.

In Keen and with my playing style at least, it makes the game more error-prone: tap on the wrong digit, then tap on the correct digit… it does not work anymore because after the first tap the cursor is gone, I need to tap on the right cell, with an extra risk of tapping next to it.

Please consider reverting the change that makes the cursor go away or add an option to keep it (or just extend the existing option to cover green marks too).

Thanks.

**Comment by rocurley** [comment]
This actually causes 2 problems for me. There's the issue mentioned above about erroneous input. But also, if I'm making a guess in keen (which you sometimes need to do on higher difficulties), I like to add and delete my guess 3 or 4 times, to create a clear maker in my undo history in case the guess is wrong. This is much harder to do after this change.

**Comment by Tadrisa** [comment]
Agreed with both of you, but for the game Towers! I do the toggle back and forth rocurley mentioned to identify guesses in my undo history in Towers, and I also accidentally tap the wrong number like Cigaes mentioned and already feel like my thumb is going all over the screen too much as it is without having to reclick boxes I just selected. I miss this old feature.
