### ISSUE TITLE
Menu issues when first loading a game, fails to draw over phone's menu screen after winning

### ISSUE THREAD

**Issue by Hatkeshiator** [chrisboyle/sgtpuzzles#632]
**Describe the bug**
App opens fine, main menu not buggy, but when opening a game, the top menu (including show hints and change parameters buttons) do not appear. Once a game is played to completion, the top menu reappears. However, at the same time, the bottom navigation buttons of my phone reappear and draw over the controls of the game itself. 

The inability to access hints or new puzzle or parameters ingame after selecting it from the menu is a major inconvenience.

**Screenshots**
![Screenshot_2023-12-25-02-10-56-58.jpg](https://github.com/chrisboyle/sgtpuzzles/assets/143983431/c1bb0570-f600-4195-acb5-6e3e262e163e)

![Screenshot_2023-12-25-02-11-36-08.jpg](https://github.com/chrisboyle/sgtpuzzles/assets/143983431/3b1f23e0-06be-4ad0-a051-b3ea2e634f0a)

![Screenshot_2023-12-25-02-11-42-61.jpg](https://github.com/chrisboyle/sgtpuzzles/assets/143983431/e3938d12-c63a-4ed1-b317-9953e899564f)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: Oppo A15 (I think?)
 - Android version: 10, security patch level Feb 5th 2023
 - App version Version 2023-11-15-2237-96d65e85

**Comment by chrisboyle** [comment]
Thanks for your report. This is unusual, in fact I don't think anyone else has ever reported these particular symptoms. I have two theories:

1. Perhaps you have the "Full screen" setting turned on in Puzzles Settings -> Display and input -> Full screen? That's the only thing in the Puzzles codebase that tries to do anything similar, and it works correctly for me (hides navigation elements but not Puzzles' own action bar) but perhaps there's a bad interaction with your particular device?

2. Alternatively, does your device have any kind of "game mode" or "game dashboard" that might be automatically activated during play, and if so can you disable it? I've seen Puzzles run correctly on devices that have such a thing, but again maybe something is different about your particular device.

**Comment by Hatkeshiator** [comment]
It was Full Screen. I turned it off and the problem is resolved now. Thank you for your answer.

I will note that I had had fullscreen on for a long time with no issues. Whatever the problem is, it is fairly recent.

I am curious about the source of this interaction. If it can be tested on other devices, maybe we could get an answer.
