### ISSUE TITLE
Rectangle: some valid solutions are not accepted

### ISSUE THREAD

**Issue by berteh** [chrisboyle/sgtpuzzles#634]
**Describe the bug**
In' 'rectangle' game some delimited areas with proper surface are not detected as valid, and this the correct domain is not accepted.

**Expected behavior**
Any area with required surface should be accepted/highlighted, even if different from expected solution..

**Screenshots**
![Screenshot_20231229-091434](https://github.com/chrisboyle/sgtpuzzles/assets/36950/a0b7b542-cbce-489f-8094-30ba2ba3538d)

All areas left should be valid too, as-is.

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: blackview bv6200
 - Android version: 13
 - App version : 2023-02-10-1537-bd5c0a37-fdroid

**Comment by berteh** [comment]
To reproduce simply change the shape of bigger groups to spot some surfaces that are not accepted, eg here top right '3' zone, modified from advertiser's solution of 1st post in this issue report.
![Screenshot_20231229-091659](https://github.com/chrisboyle/sgtpuzzles/assets/36950/33f9d51c-3647-43b5-a2f3-145f27743482)

**Comment by berteh** [comment]
Bug confirmed in Version 2023-11-15-2237-96d65e85

**Comment by SteffenBauer** [comment]
Quoting the [rules](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/rect.html#rect) :
> Your task is to subdivide the grid into **rectangles** of various sizes

So I don't think the provided screenshots are valid solutions, as the areas there aren't rectangles? Only the rectangular areas are correctly shaded in dark grey.

**Comment by JupiLogy** [comment]
The "filling" game has rules closer to what you may be expecting :)

**Comment by berteh** [comment]
My bad. Thanks for pointing out my mistake, and happy new year!
