### ISSUE TITLE
Slant (alternate solutions)

### ISSUE THREAD

**Issue by Mystimel** [chrisboyle/sgtpuzzles#639]
I did the first slant puzzle and met all the criteria but it didnt mark it solved. It seems to be an alternate solution. Here is a picture of my solution and the solution given from the app.

![Screenshot_20240210-230249_Puzzles](https://github.com/chrisboyle/sgtpuzzles/assets/159682577/4c5efbbb-7e78-4f21-b786-ad3d2a02ed7d)
![Screenshot_20240210-230300_Puzzles](https://github.com/chrisboyle/sgtpuzzles/assets/159682577/39ea0564-ddb5-4120-8cc9-6ba09abe7e91)

**Comment by chrisboyle** [comment]
You have a "1" clue with no edges connected to it:

![slant-639](https://github.com/chrisboyle/sgtpuzzles/assets/127305/3a742bc0-a235-47f7-a8bd-b8b49af10072)

**Comment by Mystimel** [comment]
Thank you! Sorry I missed that. Very challenging puzzle :)
