### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by shockergit** [chrisboyle/sgtpuzzles#645]
App icon not showing in list.

**Comment by chrisboyle** [comment]
Thanks for your report; can you be more specific? Has a shortcut vanished from your home screen, or do you mean the list of all available apps, or the list of recently opened apps? Is it just the icon or is the entry missing entirely? If you go to Settings -> Apps -> "See all [...] apps", does it appear there?

Nobody else has recently reported anything like this, so it might be something that has only happened to your device.

**Comment by shockergit** [comment]
> Thanks for your report; can you be more specific? Has a shortcut vanished from your home screen, or do you mean the list of all available apps, or the list of recently opened apps? Is it just the icon or is the entry missing entirely? If you go to Settings -> Apps -> "See all [...] apps", does it appear there?
> 
> Nobody else has recently reported anything like this, so it might be something that has only happened to your device.

its fixed after rebooting icon is showing in app drawer. something to do with custom launcher
