### ISSUE TITLE
[Feature Request]: True Black for Night Mode (Dark Theme) for Better Visuals and less Power Consumption

### ISSUE THREAD

**Issue by NA0341** [chrisboyle/sgtpuzzles#646]
Please don't forget to correct colors in the games as well :)

**Comment by chrisboyle** [comment]
Hi, thanks for your report. This is something that different users might disagree on, so it should be a setting: please follow #20 for future features around colour customisation. Simon has mentioned that he plans to add colour preferences upstream, so I will wait for that to happen before I add anything on Android.
