### ISSUE TITLE
Galaxies: Win game if all arrow markers are placed correctly

### ISSUE THREAD

**Issue by nightgolfer** [chrisboyle/sgtpuzzles#647]
**Is your feature request related to a problem? Please describe.**

I love Galaxies, and play many games each day. I mainly use an 8x16 custom grid on Unreasonable (to maximize screen use on my phone), with the following strategy:

1) Marker Mode — Place all arrow markers for dots that are on lines (doubles) or in intersections (quads).

2) Line Mode — Place all lines as dictated by markers and edges.

3) Marker Mode — Start fleshing out the grid with markers, usually to completion.

When the grid is completely full of markers, it usually means that I've solved the puzzle (unless I've managed to place one or more markers wrong somehow).

I guess I'm a bit of a completionist, so I now have to switch to Line Mode to do the grunt-work of getting the game to the Win state, instead of just starting a new game. Gotta get that screen-flash dopamine fix!

**Describe the solution you'd like**

I'd love an option/toogle in **Settings > Galaxies** that would allow Galaxies to reach the Win state if all my markers are correctly placed.

When enabled, the game checks if all markers are correctly placed when all cells (that aren't closed off already) have been filled with markers.

If all cells have been filled with markers, or closed off, and there are incorrectly placed markers, nothing happens, and I can start trouble-shooting.

If all markers have been correctly placed, the screen flashes and the Completed! menu appears.

**Describe alternatives you've considered**
None.

**Additional context**
Game version number Version 2023-11-15-2237-96d65e85

**Comment by chrisboyle** [comment]
Hi, thanks for your report. I just noticed we already have #396 for this so let's track it there.
