### ISSUE TITLE
[Feature Request] Untangle - allow board to fill screen

### ISSUE THREAD

**Issue by nightgolfer** [chrisboyle/sgtpuzzles#648]
**Is your feature request related to a problem? Please describe.**

The "game board" for untangle is square, and adds some constraints by not using the available screen space that I personally don't feel add anything to the game.

**Describe the solution you'd like**

I think an option in the Untangle settings to toggle "allow board to fill screen" would be nice.

**Describe alternatives you've considered**

I've considered either the board size constraint adds necessary complexity to the game, and I don't feel like it does.

**Additional context**

None.

**Comment by chrisboyle** [comment]
Hi, thanks for your report. We already have issue #635 for this, so please follow that issue for any further discussion. Probably the hardest thing about it is retaining compatibility with upstream, including the ability to trivially accept future changes from upstream, which is a must-have for me.

**Comment by nightgolfer** [comment]
Sorry, I didn't do a proper search for this one before posting, not very smart.

Definitely the same issue, I'll keep an eye on that one 😊👍
