### ISSUE TITLE
No numbers to press on Solo/Sudoku

### ISSUE THREAD

**Issue by ChildishGiant** [chrisboyle/sgtpuzzles#653]
**Describe the bug**
When playing Solo on my phone there are no buttons on screen to type numbers. My guess is that it's due to my phone having a built-in keyboard (I would rather use on screen buttons as the numbers require holding down alt)

**To Reproduce**
1. Open Solo

**Expected behavior**
"Also note that where this manual refers to pressing a letter on the keyboard, the Android version has icons at the bottom of the screen instead"

**Screenshots**

![Screenshot_20240331-223055_1.png](https://github.com/chrisboyle/sgtpuzzles/assets/13716824/0a723685-561d-4dcd-aeb7-4f358cfb0845)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: Unihertz Titan Slim
 - Android version: 11 
 - App version: Version 2024-03-10-2312-80aac310-fdroid

**Comment by ChildishGiant** [comment]
![Screenshot_20240331-232531.png](https://github.com/chrisboyle/sgtpuzzles/assets/13716824/8ce02423-2ab1-46a6-8e52-7370ce10de50)

I also seem to have this problem in Unequal.

**Comment by chrisboyle** [comment]
Hi, thanks for your report. This is basically #563 (as per recent edits), so let's track it there. This falls under the "add a preference" part of that issue, although that issue also tracks getting better detection of what's a real keyboard vs e.g. a headset with buttons.
