### ISSUE TITLE
Light Up Impossible Puzzle

### ISSUE THREAD

**Issue by UsavyProject** [chrisboyle/sgtpuzzles#665]
**Describe the bug**
impossible puzzle and solution show weird answer (light without any light bulb)

**To Reproduce**
1. Go to puzzle light up of Version 2024-03-29-2245-fd304c53
2. Click on 'show answer'
3. Remove all light lamp bulb
4. See error (still has light on screen)

**Expected behavior**
Shouldn't be light without light bulb

**Screenshots**
![Screenshot_2024-07-24-18-14-07-38_57594183e98acbd5c528e733d62aa74f.jpg](https://github.com/user-attachments/assets/dbb8c130-6c4e-4f34-840d-85f620baf62c)

**Version info (optional, but sometimes helpful)**
-

**Additional context**
-

**Comment by chrisboyle** [comment]
Hi, can you please attach the saved game file for this? (checkerboard menu -> Save, or Share)

**Comment by UsavyProject** [comment]
I found out the problem, Thank you very much
