### ISSUE TITLE
Minesweeper puzzle forces guesses

### ISSUE THREAD

**Issue by Freakazao** [chrisboyle/sgtpuzzles#669]
**Describe the bug**
I generated a game that I am certain requires you to guess

**To Reproduce**
1. Go to https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/mines.html#9x9:4,4,m00b7d48a3e0231c419200

**Expected behavior**
The game description says I won't need to guess

**Screenshots**
![Screenshot_2024-10-01-20-09-17-44_57594183e98acbd5c528e733d62aa74f](https://github.com/user-attachments/assets/b8f5c090-5418-454e-b953-23d9d149dabe)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: [e.g. Pixel 6]
 - Android version: [e.g. 12]
 - App version: Version 2024-03-29-2245-fd304c53

**Additional context**

**Comment by doopl** [comment]
You can reveal another square near the 1 by using logic similar to that which was used to reveal the 3.

**Comment by SteffenBauer** [comment]
Quite sure not. I solved the puzzle without guessing.

Starting point in your posted screenshot:
The '2' below the '4' on the left side of the opened block has exactly one additional mine around it. This mine is also shared with the '1' below the '2'. Ergo: The grid space diagonal to left/down to the '1' must be empty.
